title: My first Page
author: GitHub Lautaro496
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Improving day by day 

# social links
twitter_username: I-dont-use-it-much # DO NOT include the @ character, or else the build will fail!
github_username:  Lautaro-496 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
